services:
  yo:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: 2281337
      POSTGRES_DB: CardTraderDB
#      PGDATA: /var/lib/postgresql/data
#    volumes:
#      - postgres_data:/postgres
    ports:
      - "5499:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    image: syantrywave/exchange:1.1.1
    env_file:
      - .env
    restart: always
    depends_on:
      - yo
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 300M
#  yo_db:
#    image: postgres
#    env_file:
#      - db.env
#    #    restart: always
#    ports:
#      - "5422:5432"
#    environment:
#      - POSTGRES_USERNAME=postgres
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=blog
