services:
  yo:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: 2281337
      POSTGRES_DB: CardTraderDB
    ports:
      - "5499:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    image: syantrywave/exchange:1.2.0
    env_file:
      - .env
    restart: always
    depends_on:
      - yo
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 300M

