#db
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    test-connection: true

  sql:
    init:
      mode: always

aws:
  access-key: ${AWS_ACCESS-KEY}
  secret-key: ${AWS_SECRET-KEY}
  region: ${AWS_REGION}
  endpoint: ${AWS_ENDPOINT}


server:
  host: ${SERVER_HOST}
  ssl:
    enabled: true
    key-alias: ${KEY_ALIAS}
    key-store: classpath:server.keystore
    key-store-type: ${KEY_STORE_TYPE}
    key-store-password: ${KEY_PASSWORD}
    key-password: ${KEY_STORE_PASSWORD}


  error:
    include-message: always
    include-stacktrace: never




jwt:
  secret: ${SECRET}