create table  IF NOT EXISTS users
(
    id              integer generated by default as identity
        primary key,
    login           varchar(30)                                     not null
        unique,
    password        varchar(80)                                     not null,
    name            varchar(30),
    email           varchar(50)                                     not null
        unique,
    is_in_ban       boolean                                         not null,
    surname         varchar(40) default 'иванов'::character varying not null
);



create table IF NOT EXISTS users_to_be_confirmed
(
    id              integer generated by default as identity
        primary key,
    login           varchar(30) not null
        unique,
    password        varchar(80) not null,
    name            varchar(30),
    email           varchar(50) not null
        unique,
    is_in_ban       boolean,
    surname         varchar(80) not null
);



