create table  IF NOT EXISTS users
(
    id              integer generated by default as identity
        primary key,
    login           varchar(30)                                     not null
        unique,
    password        varchar(80)                                     not null,
    name            varchar(30),
    email           varchar(50)                                     not null
        unique,
    is_in_ban       boolean                                         not null,
    surname         varchar(40) default 'иванов'::character varying not null
);



create table IF NOT EXISTS users_to_be_confirmed
(
    id              integer generated by default as identity
        primary key,
    login           varchar(30) not null
        unique,
    password        varchar(80) not null,
    name            varchar(30),
    email           varchar(50) not null
        unique,
    is_in_ban       boolean,
    surname         varchar(80) not null
);
create table IF NOT EXISTS houses(
                       id  integer generated by default as identity primary key,
                       description varchar(512),
                       city varchar(32) not null ,
                       address varchar(128) not null,
                       user_id int references users(id)
);

create table IF NOT EXISTS trades(
                       id  integer generated by default as identity primary key,
                       given_house int references houses(id),
                       received_house int references houses(id),
                       start_date date,
                       end_date date,
                       status VARCHAR(20) NOT NULL DEFAULT 'ожидает ответа'
);

-- INSERT INTO users (login, password, name, email, is_in_ban)
-- SELECT 'nikitos',
--        '$2a$10$u7JP6SAu7jqlK3SrEI4o4eQnBkdXU8lw4usGH3/f72mOS12d8jguW',
--        'nikitos',
--        'nikitos@mail.ru',
--        false
-- Where not exists(select * from users where id = 1)
-- ON CONFLICT DO NOTHING;
-- INSERT INTO users (login, password, name, email, is_in_ban)
-- SELECT 'n',
--        '$2a$10$u7JP6SAu7jqlK3SrEI4o4eQnBkdXU8lw4usGH3/f72mOS12d8jguW',
--        'n',
--        'nikitos123@mail.ru',
--        false
-- Where not exists(select * from users where id = 2)
-- ON CONFLICT DO NOTHING;